SAAS-25381
Smarsh/delivery-pop-automation pull request #2
Opened 2022-11-22 09:15 UTC by floriov

2022-11-23 10:06 UTC, jpsmoura requested changes

2022-11-23 10:06 UTC, jpsmoura commented on ci/nuke-pipeline.yml
> +      - set_pipeline: nuke-pipeline
Pipeline name will contain the environment. `nuke-pipeline-((customer))-((tier))`

2022-11-23 10:06 UTC, jpsmoura commented on ci/nuke-pipeline.yml
>        ignore_paths: [version, delivery-ea-tenants-resource]
These paths don't exist in this repo.

2022-11-23 10:06 UTC, jpsmoura commented on ci/tasks/nuke-fleet-pipeline/task.sh
>  region=us-west-2
remove this var.
Make sure that you validate the env vars that are being sent. We have examples in other tasks. i.e. env var must be provided

REGION
CONCOURSE_USERNAME
CONCOURSE_PASSWORD
CUSTOMER
TIER
all vars used in a task

2022-11-23 10:06 UTC, jpsmoura commented on ci/tasks/pipeline-nuke-credhub-secrets/task.sh
> +credhub find -n ${CUSTOMER} | grep name: | cut -c9- | xargs -I {} credhub delete -n {}
this is going to delete all the entries for a particular customer which is incorrect. you need to filter by tier as well

2022-11-23 10:06 UTC, jpsmoura commented on ci/tasks/pipeline-nuke-github-commits/task.sh
> +    TENANT_ID=$(curl --location --request GET "${API_URL}/tenants?page=0&size=1&customer-name=${CUSTOMER}" \
this is not unique, you have multiple deployments for a customer

2022-11-23 10:39 UTC, SachinKainthSmarsh commented on ci/nuke-pipeline.yml
> +      - set_pipeline: nuke-pipeline
@jpsmoura Would we not also need tenant name in the pipeline so that we have one pipeline per tenant and so are able to delete a single tenant?

2022-11-23 10:56 UTC, SachinKainthSmarsh commented on ci/tasks/pipeline-nuke-apps/task.sh
> -cf login -a api.sys.us-west-2.aws.smarsh.cloud -u ${CF_USERNAME} -p ${CF_PASSWORD} -o platform -s platform-product-services
Add sys back in.

2022-11-23 10:57 UTC, SachinKainthSmarsh commented on ci/tasks/pipeline-nuke-apps/task.sh
> +cf login -a api.${REGION}.aws.smarsh.cloud -u ${CF_USERNAME} -p ${CF_PASSWORD} -o platform -s platform-data-services
sys

2022-11-23 10:58 UTC, SachinKainthSmarsh commented on ci/tasks/pipeline-nuke-bosh-deployments/task.sh
> +if [ "$bosh_${CUSTOMER}_exists" -eq 0 ];
same here

2022-11-23 11:21 UTC, SachinKainthSmarsh commented on ci/tasks/pipeline-nuke-github-commits/task.sh
> +    TENANT_ID=$(curl --location --request GET "${API_URL}/tenants?page=0&size=1&customer-name=${CUSTOMER}" \
@jpsmoura So we would need to support nuking for different regions and tiers right?

2022-11-23 11:25 UTC, SachinKainthSmarsh commented on ci/tasks/pipeline-nuke-github-commits/task.sh
> +      git commit -m ":sparkler:	Pipeline - Reverted vars files"
Shall we replace this with ${CUSTOMER}?

2022-11-23 11:25 UTC, SachinKainthSmarsh commented on ci/tasks/pipeline-nuke-github-commits/task.sh
> +  ${CUSTOMER}_exists=$(cat config/enterprise-archive/spaces.yml | grep "${CUSTOMER}" >>/dev/null 2>&1;echo $?)
customer_exists

2022-11-23 11:27 UTC, SachinKainthSmarsh commented on ci/tasks/pipeline-nuke-github-commits/task.sh
> +  if [ "${CUSTOMER}_exists" -eq 0 ];
customer_exists

2022-11-23 11:28 UTC, SachinKainthSmarsh commented on ci/tasks/pipeline-nuke-credhub-secrets/task.sh
> +credhub find -n ${CUSTOMER} | grep name: | cut -c9- | xargs -I {} credhub delete -n {}
poplite-nam-archive-production
white_check_mark
eyes
raised_hands::skin-tone-4





[11:14](https://smarsh.slack.com/archives/D03HWF7LJFK/p1669202091425479)
poplite-production
white_check_mark
eyes
raised_hands::skin-tone-4





[11:14](https://smarsh.slack.com/archives/D03HWF7LJFK/p1669202098373109)
poplite/production
white_check_mark
eyes
raised_hands::skin-tone-4





[11:15](https://smarsh.slack.com/archives/D03HWF7LJFK/p1669202134347329)
credhub set -n /concourse/platform-delivery-services/${CUSTOMER} -t 'value' --value ${CUSTOMER}
credhub find -n ${CUSTOMER} | grep name: | cut -c9- | xargs -I {} credhub delete -n {}

2022-11-23 11:29 UTC, SachinKainthSmarsh commented on ci/tasks/pipeline-nuke-github-commits/task.sh
> +    git commit -m ":sparkler:	Pipeline - Reverted enterprise archive files"
same here

2022-11-23 11:33 UTC, SachinKainthSmarsh commented on ci/tasks/pipeline-nuke-github-commits/task.sh
> +  find . -name '*${CUSTOMER}*' -exec git rm {} \;
General comment: All of the code here may need to take into account region and tier as well.

2022-11-23 11:33 UTC, SachinKainthSmarsh commented on ci/tasks/pipeline-nuke-github-commits/task.sh
> +    git commit -m ":sparkler:	Pipeline - Revert deployment files"
same

2022-11-23 11:34 UTC, SachinKainthSmarsh commented on ci/tasks/pipeline-nuke-github-commits/task.sh
> -  rm -rf ea-platform-sre-team
Make sure this is not required - compare with old version.

2022-11-23 11:35 UTC, SachinKainthSmarsh commented on ci/tasks/pipeline-nuke-slack-channel/task.sh
> +${CUSTOMER}_CHANNEL_NAME='${CLOUD}-${REGION}-${CUSTOMER}-${TIER}'
CUSTOMER_CHANNEL_NAME

2022-11-23 11:35 UTC, SachinKainthSmarsh commented on ci/tasks/pipeline-nuke-slack-channel/task.sh
> +curl --location --request POST "https://slack.com/api/admin.conversations.search?query=${${CUSTOMER}_CHANNEL_NAME}" \
CUSTOMER_CHANNEL_NAME

2022-11-23 11:35 UTC, SachinKainthSmarsh commented on ci/tasks/pipeline-nuke-slack-channel/task.sh
> +if [ "$channel_name" = "${CUSTOMER}_CHANNEL_NAME" ]; then
CUSTOMER_CHANNEL_NAME

2022-11-23 11:36 UTC, SachinKainthSmarsh commented on ci/tasks/pipeline-nuke-spaces/task.sh
> +  echo -e ${GREEN}"Check if the ${CUSTOMER}-production space exists"${WHITE}
same

2022-11-23 11:36 UTC, SachinKainthSmarsh commented on ci/tasks/pipeline-nuke-spaces/task.sh
> +delete_${CUSTOMER}_space enterprise-archive
same

2022-11-23 11:38 UTC, SachinKainthSmarsh commented on ci/vars/platform-delivery-staging-aws-us-west-2.yml
> +tier: production
Needs to be uat or staging.  Create a new vars file for prod

2022-11-23 16:17 UTC, jpsmoura commented on ci/nuke-pipeline.yml
> +      - set_pipeline: nuke-pipeline
this pipeline deletes infrastructure, pipelines and secrets for a particular deployment. We might need different nuke pipelines for a tenant within a deployment, but that will be a different effort

2022-11-28 10:02 UTC, jpsmoura requested changes

2022-11-28 10:02 UTC, jpsmoura commented on ci/tasks/pipeline-nuke-apps/task.sh
> +export REGION=${REGION}
You don't need to export params passed to your tasks, they are already environment variables. What you can do is validated that they are being passed

2022-12-05 15:11 UTC, SachinKainthSmarsh approved these changes

2022-12-05 15:11 UTC, merged